import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {
  Box,
  Button,
  Container,
  Divider,
  Grid,
  Stack,
  Typography,
} from "@mui/material";
import BannerSection from "@/components/bannerSection";
import waveLine from "@/images/waveLine.png";
import Services from "@/components/services";
import data from "@/assets/data";
import HeadingPrefix from "@/components/headingStarter";
import aboutImage1 from "@/images/aboutimage2.png";
import aboutImage2 from "@/images/aboutimage1.png";
import Contact from "@/components/contact";
import Counter from "@/components/counter";
import ClientTestimonial from "@/components/clientTestimonial";
import TeamSection from "@/components/teamSection";
import contact from "@/images/contact-image.png";
import Brands from "@/components/brands";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="home">
        <BannerSection />
      </div>
      {/* <div className={styles.wave}>
      </div> */}
      <div id="services" className={styles.wave}>
        <Stack
          direction={"row"}
          alignItems={"center"}
          justifyContent={"center"}
          spacing={2}
          mt={10}
        >
          <HeadingPrefix />
          <Typography
            textTransform={"uppercase"}
            fontSize={15}
            fontWeight={550}
          >
            {" "}
            Our Services
          </Typography>
          <HeadingPrefix />
        </Stack>
        <Typography
          fontSize={55}
          textAlign={"center"}
          fontWeight={600}
          letterSpacing={2}
          mt={4}
        >
          Service We Provide
        </Typography>
        <Grid container>
          <Grid items lg={5} margin={"auto"}>
            <Typography
              fontSize={16}
              textAlign={"center"}
              color="#a6a8ae"
              fontWeight={500}
              mt={4}
            >
              we deliver expert IT services and consulting, including managed
              IT, cybersecurity, and cloud solutions.
            </Typography>
          </Grid>
        </Grid>
        <Container sx={{ mt: 10 }}>
          <Grid container spacing={3}>
            {data.services.map((val, i) => (
              <Grid item lg={3} key={i}>
                <Services
                  img={val.img}
                  heading1={val.heading1}
                  heading2={val.heading2}
                  description={val.description}
                />
              </Grid>
            ))}
          </Grid>
        </Container>
      </div>
      <div id="about">
        <Container sx={{ mt: 10 }}>
          <Grid container spacing={3} alignItems={"center"}>
            <Grid item lg={6}>
              <Stack direction={"row"} alignItems={"center"} spacing={2}>
                <HeadingPrefix />
                <Typography fontSize={15} fontWeight={550}>
                  WELCOME TO OUR COMPANY
                </Typography>
              </Stack>
              <Typography fontSize={45} fontWeight={550} mt={2}>
                We Are Increasing Business Success With Technology
              </Typography>
              <Typography mt={2} color={"grey"} fontSize={16} fontWeight={500}>
                An IT solution service company may serve clients from various
                industries such as healthcare, finance, education, and
                manufacturing. They may work on a project basis, providing
                services for a specific project or on a long-term
                basis...Amazing communication.Best trending designing
                experienceEmail & Live chat.
              </Typography>
            </Grid>
            <Grid item lg={6} textAlign={"end"}>
              <Image src={aboutImage1} width={500} />
              <Box sx={{ position: "relative" }}>
                <Image
                  src={aboutImage2}
                  className={styles.aboutImageSection}
                  width={250}
                />
              </Box>
            </Grid>
          </Grid>
        </Container>
        <Box className={styles.consultation_wrapper} sx={{ mt: 10 }}>
          <Container maxWidth="lg">
            <Grid container alignItems={"center"}>
              <Grid item lg={6}>
                <Typography sx={{ color: "#fff", fontWeight: "550" }}>
                  WE ARE HERE TO ANSWER YOUR QUESTIONS 24/7
                </Typography>
                <Typography fontSize={50} color={"#fff"}>
                  Need A Consultation?
                </Typography>
              </Grid>
              <Grid item lg={6} textAlign={"end"}>
                <Button
                  sx={{
                    border: "1px solid #0e59f2",
                    color: "#fff",
                    backgroundColor: "#0e59f2",
                    borderRadius: 20,
                    p: 2,
                    ":hover": {
                      color: "#fff",
                      backgroundColor: "#222",
                      border: "1px solid #222",
                    },
                    fontWeight: 550,
                  }}
                >
                  Let's Get Started
                </Button>
              </Grid>
            </Grid>
          </Container>
        </Box>
        <Container maxWidth="lg" sx={{ mt: 10 }}>
          <Contact />
        </Container>

        <Container maxWidth="lg" sx={{ mt: 10 }}>
          <Divider />
          <Box mt={10}>
            <Grid container spacing={2} alignItems={"center"}>
              {data.counterText.map((val, i) => (
                <Grid item lg={3} key={i}>
                  <Counter img={val.img} end={val.end} heading={val.heading} />
                </Grid>
              ))}
            </Grid>
          </Box>
        </Container>
        <Box sx={{ mt: 10 }}>
          <ClientTestimonial />
        </Box>
      </div>
      <div id="team">
        <Container sx={{ mt: 10 }} maxWidth="lg">
          <Stack
            direction={"row"}
            alignItems={"center"}
            justifyContent={"center"}
            spacing={2}
          >
            <HeadingPrefix />
            <Typography fontSize={15} fontWeight={600}>
              TEAM MEMBERS
            </Typography>
            <HeadingPrefix />
          </Stack>
          <Typography
            fontSize={45}
            fontWeight={600}
            textAlign={"center"}
            mt={2}
          >
            Our Top Skilled Experts
          </Typography>
          <Grid container spacing={2} mt={2}>
            {data.teams.map((val, i) => (
              <Grid item lg={3}>
                <TeamSection
                  img={val.img}
                  designation={val.designation}
                  name={val.name}
                  socialAccounts={val.socialAccounts}
                />
              </Grid>
            ))}
          </Grid>
        </Container>
      </div>
      <div id="contact">
        <Box className={styles.contact_Banner} sx={{ mt: 10 }}>
          <Container maxWidth="lg">
            <Grid container alignItems={"center"}>
              <Grid item lg={6}>
                <Stack direction={"row"} alignItems={"center"} spacing={2}>
                  <HeadingPrefix />
                  <Typography fontSize={15} fontWeight={550}>
                    START WORK WITH US
                  </Typography>
                </Stack>
                <Typography fontSize={45} fontWeight={550} mt={2}>
                  The Best{" "}
                  <Typography variant="span" color={"#105af2"}>
                    IT Service
                  </Typography>
                  <br /> Provider.
                </Typography>
                <Typography
                  mt={2}
                  color={"#9397a2"}
                  fontSize={16}
                  fontWeight={500}
                >
                  Managed IT services can help you outsource your IT needs to a
                  third-party provider. This includes IT support, network
                  monitoring, and maintenance, and disaster recovery and
                  business continuity planning.
                </Typography>
                <Button
                  sx={{
                    mt: 2,
                    border: "1px solid #105af2",
                    backgroundColor: "#105af2",
                    borderRadius: 20,
                    p: 2,
                    width: 200,
                    color: "#fff",
                    ":hover": {
                      color: "#fff",
                      backgroundColor: "#222",
                    },
                  }}
                >
                  Let's get started{" "}
                </Button>
              </Grid>
              <Grid item lg={6} textAlign={"center"}>
                <Image src={contact} height={600} />
              </Grid>
            </Grid>
          </Container>
        </Box>
        <Container sx={{ mt: 10 }}>
          <Stack
            direction="row"
            alignItems={"center"}
            spacing={2}
            justifyContent={"center"}
          >
            <HeadingPrefix />
            <Typography sx={{ fontSize: 15, fontWeight: 600 }}>
              BRAND WE WORK WITH
            </Typography>
            <HeadingPrefix />
          </Stack>
          <Typography
            sx={{ fontSize: 45, fontWeight: 550, textAlign: "center", mt: 2 }}
          >
            Trusted by thousands Business
          </Typography>
          <Grid container mt={3}>
            {data.brands.map((val, i) => (
              <Grid item lg={3} key={i}>
                <Brands img={val.img} />
              </Grid>
            ))}
          </Grid>
        </Container>
      </div>
    </>
  );
}
