import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Box, Container, Grid, Stack, Typography } from "@mui/material";
import BannerSection from "@/components/bannerSection";
import waveLine from "../../public/images/waveLine.png";
import Services from "@/components/services";
import data from "@/assets/data";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="home">
        <BannerSection />
      </div>
      {/* <div className={styles.wave}>
      </div> */}
      <div id="services" className={styles.wave}>
        <Stack
          direction={"row"}
          alignItems={"center"}
          justifyContent={"center"}
          spacing={2}
          pt={10}
        >
          <Box
            sx={{
              backgroundColor: "#0e59f2",
              width: 7,
              height: 7,
              borderRadius: 0.3,
            }}
          ></Box>{" "}
          <Typography
            textTransform={"uppercase"}
            fontSize={15}
            fontWeight={550}
          >
            {" "}
            Our Services
          </Typography>
          <Box
            sx={{
              backgroundColor: "#0e59f2",
              width: 7,
              height: 7,
              borderRadius: 0.3,
            }}
          ></Box>{" "}
        </Stack>
        <Typography
          fontSize={55}
          textAlign={"center"}
          fontWeight={600}
          letterSpacing={2}
          mt={4}
        >
          Service We Provide
        </Typography>
        <Grid container>
          <Grid items lg={5} margin={"auto"}>
            <Typography
              fontSize={16}
              textAlign={"center"}
              color="#a6a8ae"
              fontWeight={500}
              mt={4}
            >
              we deliver expert IT services and consulting, including managed
              IT, cybersecurity, and cloud solutions.
            </Typography>
          </Grid>
        </Grid>
        <Container sx={{ mt: 10}}>
          <Grid container spacing={3}>
            {data.services.map((val, i) => (
              <Grid item lg={3} key={i}>
                <Services
                  img={val.img}
                  heading1={val.heading1}
                  heading2={val.heading2}
                  description={val.description}
                />
              </Grid>
            ))}
          </Grid>
        </Container>
      </div>
      <div id="about">
        <Box sx={{ height: 500 }}>About</Box>
      </div>
    </>
  );
}
